spring.application.name=message-service

spring.mongodb.host=${DB_HOST:localhost}
spring.mongodb.port=${DB_PORT:27017}
spring.mongodb.database=${DB_NAME:message_service}
spring.mongodb.authentication-database=${DB_AUTH_SOURCE:admin}
spring.mongodb.username=${DB_USERNAME:admin}
spring.mongodb.password=${DB_PASSWORD:password}
server.port=8084

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:password}
redis.chat.user.ttl.minute=5
redis.chat.user.pattern=chatId:%s:userId:%s

CHAT_SERVICE_URL=http://localhost:8083
REACTION_SERVICE_URL=http://localhost:8085
MEDIA_SERVICE_URL=http://localhost:8086
INTERNAL_API_KEY=internal_api_key

spring.kafka.bootstrap-servers=localhost:9092

kafka.group.delete.chat=warehouse-group-delete-chat
kafka.topic.delete.chat=chat-delete

kafka.topic.chat=chat-messages
kafka.topic.gateway.messageEvents=gateway-message-events
kafka.topic.delete.message=message-delete
