spring.application.name=media-service
server.error.include-message=always
server.error.include-exception=true

server.port=8086

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=52MB

yandex.disk.token=${DISK_TOKEN:}

internal.api.key=internal_api_key