spring.application.name=user-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:user_details}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

AUTH_SERVICE_URL=http://localhost:8081
MEDIA_SERVICE_URL=http://localhost:8086
INTERNAL_API_KEY=internal_api_key

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka.topic.user.delete=user-delete