spring.application.name=chat-service

spring.datasource.url=jdbc:postgresql://localhost:5434/${DB_NAME:chat}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
server.port=8083

USER_SERVICE_URL=http://localhost:8082

spring.kafka.bootstrap-servers=localhost:9092

kafka.group.message=warehouse-group-message
kafka.topic.message=chat-messages

kafka.topic.delete=chat-delete

kafka.topic.user.delete=user-delete
kafka.group.user.delete=warehouse-group-user-delete
