spring.application.name=reaction-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5435/${DB_NAME:reaction}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

MESSAGE_SERVICE_URL=http://localhost:8084

spring.kafka.bootstrap-servers=localhost:9092

kafka.group.delete.message=warehouse-group-delete-message
kafka.topic.delete.message=message-delete

kafka.group.delete.chat=warehouse-group-delete-chat-reaction
kafka.topic.delete.chat=chat-delete

kafka.topic.gateway.reactionEvents=gateway-reaction-events